apiVersion: v1
kind: Service
metadata:
  name: minimal-service
  namespace: testing
spec:
  type: LoadBalancer
  ports:
    - port: 777
      targetPort: 8000
  selector:
    app: minimal-service-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minimal-service
  namespace: testing
  labels:
    app: minimal-service-app
spec:
  selector:
    matchLabels:
      app: minimal-service-app
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: minimal-service-app
    spec:
      containers:
        - image: cottoffeus/minimal_service
          name: minimal-service
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5

#          imagePullPolicy: Always|IfNotPresent|Never
#          readinessProbe:
#            httpGet:
#              path: /
#              port: 5678
#            initialDelaySeconds: 5
#            periodSeconds: 20
